### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by night-crawler** [RedisLabs/redisearch-py#9]
Hi. Could you please add Python 3 support? :)
Thank you.

**Comment by wilrich-msft** [comment]
I tried to 2to3 all the files, but while I saw no errors later on in Python 3, search did not return anything.

**Comment by glenn-edgar** [comment]
I tried running the example in the readme using python3 and got an exception call back

Traceback (most recent call last):
  File "redis_search_example_py3.py", line 41, in <module>
    res = client.search("search engine".encode())
  File "/usr/local/lib/python3.5/dist-packages/redisearch/client.py", line 302, in search
    args, query = self._mk_query_args(query)
  File "/usr/local/lib/python3.5/dist-packages/redisearch/client.py", line 283, in _mk_query_args
    if isinstance(query, (str, unicode)):
NameError: name 'unicode' is not defined

at
res = client.search("search engine")

**Comment by yuvadm** [comment]
Same error on Python 3.6

**Comment by mnunberg** [comment]
This is fixed in master

**Comment by yuvadm** [comment]
Great! Looking forward to a release as well. Thanks for the work on this.
